# Generated by Django 2.0 on 2020-02-11 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0002_auto_20200210_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('tuijian', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=50)),
                ('publisher', models.CharField(max_length=100)),
                ('pub_date',models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('num', models.IntegerField(default=10)),
                ('isbn', models.CharField(max_length=13)),
                ('context', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='bookimg',
            name='bookid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.Books'),
        ),
    ]
